' <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
Imports System

Namespace Models
	Partial Public Class Product
		Public Property id() As Integer
		Public Property title() As String
		Public Property description() As String
		Public Property availability() As String
		Public Property link() As String
		Public Property image_link() As String
		Public Property price() As String
		Public Property identifier_exists() As String
		Public Property gtin() As String
		Public Property mpn() As String
		Public Property brand() As String
		Public Property product_highlight() As String
		Public Property product_detail() As String
		Public Property additional_image_link() As String
		Public Property condition() As String
		Public Property adult() As String
		Public Property color() As String
		Public Property size() As String
		Public Property gender() As String
		Public Property material() As String
		Public Property pattern() As String
		Public Property age_group() As String
		Public Property multipack() As String
		Public Property is_bundle() As String
		Public Property unit_pricing_measure() As String
		Public Property energy_efficiency_class() As String
		Public Property min_energy_efficiency_class() As String
		Public Property item_group_id() As Integer

	End Class
End Namespace